In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df=pd.read_csv("/Users/shubhamsingh/Desktop/ML/Titanic-Dataset.csv")
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [10]:
df=df.drop(columns=["Cabin","Name","Ticket","PassengerId"])
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [11]:
df["Age"]=df["Age"].fillna(df["Age"].median())
df.dropna(subset=["Embarked"],inplace=True)

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    str
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(2)
memory usage: 62.5 KB

In [13]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
print(x_test.shape)
print(x_train.shape)

(178, 7)
(711, 7)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'female'

In [36]:
x_train.head(1)

     Pclass     Sex   Age  SibSp  Parch    Fare Embarked
708       1  female  22.0      0      0  151.55        S

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [39]:
cat_cols = ["Sex","Embarked"]

In [40]:
ct=ColumnTransformer([('cat',OneHotEncoder(sparse_output=False),cat_cols)],
                    remainder='passthrough')
x_train_final=ct.fit_transform(x_train)
x_test_final=ct.transform(x_test)

In [41]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [42]:
model=KNeighborsClassifier()
model.fit(x_train_final,y_train)
y_pre=model.predict(x_test_final)
print(accuracy_score(y_test,y_pre))

0.6853932584269663

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train_final)
x_test_scaled=scaler.transform(x_test_final)

In [46]:
scaled_model=KNeighborsClassifier()
scaled_model.fit(x_train_scaled,y_train)
y_pre_scaled=scaled_model.predict(x_test_scaled)
print("before scaling",accuracy_score(y_test,y_pre))
print("after scaling",accuracy_score(y_test,y_pre_scaled))

before scaling 0.6853932584269663
after scaling 0.7921348314606742